# Generated by Django 5.1.2 on 2025-03-31 09:18

import django.db.models.deletion
import django.utils.timezone
import djangocms_text_ckeditor.fields
import newsticker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TickerItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TickerPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TickerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('pub_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('headline', models.CharField(max_length=255)),
                ('summary', djangocms_text_ckeditor.fields.HTMLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsticker.tickercategory')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsticker.tickeritemtype')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsticker.tickerpublication')),
            ],
        ),
        migrations.CreateModel(
            name='TickerRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(choices=[('website', 'Website'), ('pdf', 'PDF'), ('video', 'Video'), ('image', 'Image')], max_length=30)),
                ('index', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True, null=True)),
                ('uploadfile', models.FileField(blank=True, null=True, upload_to=newsticker.models.tickerref_file_upload)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsticker.tickeritem')),
            ],
        ),
    ]
