# Generated by Django 5.1.2 on 2025-04-01 21:30

import djangocms_text_ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsticker', '0002_alter_tickerref_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickeritemtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tickerpublication',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='tickeritem',
            name='summary',
            field=djangocms_text_ckeditor.fields.HTMLField(help_text='Cited Work: GRÜNEN | Marker: Referenz'),
        ),
    ]
