# Generated by Django 5.1.2 on 2025-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsticker', '0004_tickeritem_has_summary_alter_tickeritem_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickeritem',
            name='has_summary',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
