# Generated by Django 5.1.2 on 2025-04-05 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsticker', '0005_alter_tickeritem_has_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerref',
            name='linked_tickeritem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tickerref_set', to='newsticker.tickeritem'),
        ),
        migrations.AlterField(
            model_name='tickerref',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickerref_set', to='newsticker.tickeritem'),
        ),
        migrations.AlterField(
            model_name='tickerref',
            name='ref_type',
            field=models.CharField(choices=[('website', 'Website'), ('pdf', 'PDF'), ('video', 'Video'), ('image', 'Image'), ('tickeritem', 'Ticker Item')], max_length=30),
        ),
    ]
