# Generated by Django 5.1.2 on 2025-04-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsticker', '0007_tickeritem_refs_in_summary_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerref',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tickerref',
            name='ref_type',
            field=models.CharField(choices=[('website', 'Website'), ('pdf', 'PDF'), ('video', 'Video'), ('image', 'Image'), ('tickeritem', 'Ticker Item'), ('abbreviation', 'Abbreviation')], max_length=30),
        ),
    ]
