# Generated by Django 5.1.2 on 2025-04-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsticker', '0008_tickerref_text_alter_tickerref_ref_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerref',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
