# Generated by Django 5.1.2 on 2025-04-24 20:52

import djangocms_text_ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsticker', '0009_tickerref_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=5)),
                ('display_date', models.DateField()),
                ('display_days', models.IntegerField(default=0)),
                ('clicks_log', models.TextField(blank=True, null=True)),
                ('clicks_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='tickeritem',
            name='summary',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Cited Work: GRÜNEN | Marker: Referenz | Variable: Mehr +/-', null=True),
        ),
    ]
