# Generated by Django 5.1.2 on 2025-04-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsticker', '0010_sharelink_alter_tickeritem_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='valid_until',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
