# Generated by Django 5.1.2 on 2025-04-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsticker', '0011_sharelink_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='shared_with_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='short',
            field=models.CharField(editable=False, max_length=5),
        ),
    ]
